### ISSUE TITLE
Can't Paint

### ISSUE THREAD

**Issue by shadpweaver** [jhaakma/joy-of-painting#3]
[MWSE.log](https://github.com/jhaakma/joy-of-painting/files/11713382/MWSE.log)

all requirements up to date, both Morrowind and Magickimage installed outside programs files
can adjust settings, move camera, ect, but pressing the paint button in game does nothing and saves no image to folder

**Comment by jhaakma** [comment]
Try using the standalone version of image magick in the downloads section of the Joy of Painting Nexus page. Extract it into your Morrowind installation folder like a regular mod.

**Comment by shadpweaver** [comment]
This fixed it, thank you
